assistant:
  name:  Chat
  model_type: text
  welcome_message: Hi, I'm <b>Antichatrime</b>. How can I help you?
  prompt_start: ""
  parse_mode: html

artist:
  name: Image
  welcome_message: Hi, I'll draw anything you write me.
